## Static
- type: latheRecipePack
  id: SecurityAmmoStaticPirate
  recipes:
  - MagazineUniversalMagnumEmpty
  - MagazineUniversalMagnum
  - MagazineUniversalMagnumRubber
  - MagazineMagnumEmpty
  - MagazineMagnum


## Dynamic
- type: latheRecipePack
  id: SecurityWeaponsPirate
  recipes:
  - WeaponPistolMk58
  - WeaponPistolUniversal
  - WeaponSubMachineGunFPA90
  - WeaponSubMachineGunBRDIR25
  - WeaponRifleVulcanM

- type: latheRecipePack
  id: SecurityAmmoPirate
  recipes:
  # 45. Mk 32
  - MagazineUniversalMagnumUranium
  - MagazineUniversalMagnumIncendiary
  - MagazineMagnumUranium
  # 9.5mm
  - MagazineCaselessRifleEmpty
  - MagazineCaselessRifle
  - MagazineCaselessRifleShort
  - MagazineCaselessRifleStandart
  - MagazineCaselessRifleStandartShort
  - MagazineBoxCaselessRifleStandart
  - MagazineBoxCaselessRifle
  # .30
  - MagazineLightRifle
  - MagazineLightRifleIncendiary
  - MagazineLightRifleUranium
  - MagazineBoxLightRifleIncendiary
  - MagazineBoxLightRifleUranium
  - MagazineBoxLightRifle