- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleShadowling
  name: "Роль Тіньовика"
  components:
  - type: MindRole
    antagPrototype: Shadowling
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: ShadowlingRole

- type: entity
  parent: MindRoleShadowling
  id: MindRoleThrall
  name: "Роль Поневоленого"
  components:
  - type: MindRole
    antagPrototype: Thrall
