- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: "опис роботи богомола"
  playTimeTracker: JobForensicMantis
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Science
      time: 3600
    - !type:SpeciesRequirement
      inverted: true
      species:
        - IPC
    # Pirate contractor start
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed
    # Pirate contractor end
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  goobcoins: 25 #Goob content
  access:
  - Research
  - Maintenance
  - Mantis
  special:
  - !type:AddComponentSpecial
    components:
      - type: CanEnchant
      - type: Psionic
        powerSlots: 2
        powerRollMultiplier: 3
        baselinePowerCost: 75
        nextPowerCost: 75
        removable: false
      - type: InnatePsionicPowers
        powersToAdd:
          - MetapsionicPower
          - TelepathyPower
          - MantisSummonBlackBlade
          - AssayPower
      - type: Telepathy

- type: startingGear
  id: ForensicMantisGear
  equipment:
    ears: ClothingHeadsetScience
    id: ForensicMantisPDA

- type: chameleonOutfit
  id: ForensicMantisChameleonOutfit
  job: ForensicMantis
  startingGear: ForensicMantisGear
  equipment:
    outerClothing: ClothingOuterCoatLab
    shoes: ClothingShoesColorBlack
