# Weather Blocker
- type: entity
  name: Marker Weather Blocker
  id: MarkerWeatherblocker
  parent: MarkerBase
  components:
  - type: Sprite
    sprite: _Pirate/Markers/environment.rsi
    state: weather
  - type: BlockWeather
