# Weather Blocker
- type: entity
  name: "Маркер блокування погоди"
  id: MarkerWeatherblocker
  parent: MarkerBase
  components:
  - type: Sprite
    sprite: _Pirate/Markers/environment.rsi
    state: weather
  - type: BlockWeather
