# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BaseMindRoleAntag
  id: DevilMindRole
  name: "Роль Диявола"
  components:
  - type: MindRole
    antagPrototype: Devil
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-devil
  - type: DevilRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: "Роль Перевертня"
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-changeling
  - type: ChangelingRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeretic
  name: "Роль Єретика"
  components:
  - type: MindRole
    antagPrototype: Heretic
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-heretic
  - type: HereticRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleGhoul
  name: "Гул"
  components:
  - type: MindRole
    antagPrototype: Ghoul
    exclusiveAntag: false
    roleType: Familiar
    subtype: role-subtype-ghoul
  - type: GhoulRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBrainwashed
  name: "Роль з промитими мізками"
  components:
  - type: MindRole
    antagPrototype: Mindcontrolled
    exclusiveAntag: true
    roleType: Familiar
    subtype: role-subtype-brainwashed
  - type: MindcontrolledRole

- type: entity
  parent: MindRoleChangeling
  id: MindRoleChangelingmidround
  name: "роль сплячого генокрада"
  components:
  - type: MindRole
    exclusiveAntag: false           #  bastard experiment

- type: entity
  parent: MindRoleHeretic
  id: MindRoleHereticmidround
  name: "роль сплячого єретика"
  components:
  - type: MindRole
    exclusiveAntag: false   # bastard experiment

- type: entity
  parent: DevilMindRole
  id: DevilMindRolemidround
  name: "роль сплячого диявола"

# Slasher
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSlasher
  name: "Роль Слешера"
  components:
  - type: MindRole
    antagPrototype: Slasher
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-slasher
