- type: entity
  parent: BaseObjective
  id: GrayTideKillEveryoneObjective
  components:
  - type: Objective
    icon:
      sprite: Objects/Tools/Toolboxes/toolbox_red.rsi
      state: icon
    difficulty: 1.5
    issuer: objective-issuer-unknown
  - type: SlaughterKillEveryoneCondition
    title: tide-objective-condition-kill-everyone-else-title
    description: tide-objective-kill-everyone-desc

- type: entity
  parent: BaseObjective
  name: "Захисти технічні тунелі."
  description: "Технічні тунелі цієї станції були твоїм домом стільки, скільки ти себе пам’ятаєш. Ховатися від екіпажу в шафках — усе, що ти знав, аж дотепер. Тепер ці станційні мешканці вторглися у твій дім востаннє: убий кожного, хто наважиться порушити спокій твого лігва."
  id: TunnelClownProtectMaintenanceObjective
  components:
  - type: Objective
    icon:
      sprite: Clothing/Mask/clown.rsi
      state: icon
    difficulty: 1
    issuer: objective-issuer-unknown
  - type: RoleplayObjective

- type: entity
  parent: BaseObjective
  name: "Проповідуй слово лорда Синґулота!"
  description: "Знайди інженерний відділ цієї станції та наверни тамтешній люд до числа послідовників Синґулота. Якщо відмовляться — страти їх без пощади."
  id: SingulothKnightPreachObjective
  components:
  - type: Objective
    icon:
      sprite: Objects/Specific/Chapel/bible.rsi
      state: icon
    difficulty: 1
    issuer: objective-issuer-lord-singuloth
  - type: RoleplayObjective

- type: entity
  parent: BaseObjective
  name: "Розшир сингулярність"
  description: "Зроби ласку лорду Синґулоту: розшир сингулярність (але не випускай її з-під контролю). Чим більша — тим краще!"
  id: SingulothKnightSingularityObjective
  components:
  - type: Objective
    icon:
      sprite: Objects/Weapons/Melee/singularityhammer.rsi
      state: icon
    difficulty: 1
    issuer: objective-issuer-lord-singuloth
  - type: RoleplayObjective

- type: entity
  parent: BaseObjective
  name: "Знищ усі тесли на станції"
  description: "Якщо на цій станції є Тесла, ти маєш знищити її будь-якими засобами та стратити її творця за таку образу лорда Синґулота!"
  id: SingulothKnightTeslaObjective
  components:
  - type: Objective
    icon:
      sprite: _Goobstation/Clothing/Head/Hardsuits/singulothhelm.rsi
      state: icon
    difficulty: 1
    issuer: objective-issuer-lord-singuloth
  - type: DestroyTheTeslaObjective

- type: entity
  parent: BaseObjective
  name: "Влаштуй епічну дуель!"
  description: "Інші агенти Синдикату не сприймають тебе всерйоз. Доведи, що вони помиляються, перемігши в дуелі гідного суперника!"
  id: DarkLordDuelObjective
  components:
  - type: Objective
    icon:
      sprite: Objects/Weapons/Melee/e_sword.rsi
      state: icon
    difficulty: 1
    issuer: objective-issuer-syndicate
  - type: RoleplayObjective

- type: entity
  parent: BaseObjective
  name: "Убий Темного лорда"
  description: "Нанотрасен відправила тебе на цю станцію, щоб убити Темного лорда. Не підведи їх!"
  id: ChosenOneKillDarkLordObjective
  components:
  - type: Objective
    icon:
      sprite: Objects/Weapons/Melee/e_sword.rsi
      state: icon
    difficulty: 1
    issuer: objective-issuer-nanotrasen
  - type: KillTheDarkLordObjective

- type: entity
  parent: BaseObjective
  name: "Найми учня"
  description: "Тобі потрібен учень — найми когось! Це не обов’язково має бути людина, яку ти захищаєш!"
  id: DarkPriestHireApprentice
  components:
  - type: Objective
    icon:
      sprite: _ShitChap/Objects/Weapons/Nullrod/nullrod.rsi
      state: icon
    difficulty: 1
    issuer: objective-issuer-self
  - type: RoleplayObjective

- type: entity
  parent: BaseKeepAliveObjective
  id: DarkPriestProtectObjective
  name: "Захищай члена екіпажу"
  description: "Захищай члена екіпажу, який привернув твою увагу."
  components:
  - type: Objective
    difficulty: 2
    icon:
      sprite: Objects/Misc/folders.rsi
      state: folder-white
    issuer: objective-issuer-self
  - type: TargetObjective
    title: objective-condition-other-alive-title
  - type: PickRandomPerson
